require("./proxy/EntryPoint.test");
require("./proxy/Proxy.test");
require("./deploy/Deployer.test");
require("./registries/AssetsRegistry.test");
require("./registries/ProjectsRegistry.test");
require("./registries/SCRegistry.test");
require("./asset/Asset.test");
require("./asset/ERC20.test");
require("./asset/RPC.test");
